# Generated by Django 5.2.7 on 2025-10-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0004_clase_instructor_socio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='clase_especialidad',
            new_name='clase_tema',
        ),
    ]
